Repository micronaut-projects/micronaut-gcp, pull requests merged in 2020-09, with the labels that each got.

#214 [gcp] Update common files for branch 2.1.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#222 Add EmbeddedServer for GCP function
  gcp-function-http-test/build.gradle
  gcp-function-http-test/src/main/java/io/micronaut/gcp/function/http/test/InvokerHttpServer.java
  gcp-function-http-test/src/test/groovy/io/micronaut/gcp/function/http/test/InvokerHttpServerSpec.groovy
  gcp-function-http-test/src/test/resources/logback.xml
  settings.gradle
Labels: type: enhancement

#229 Dependency upgrades
  doc-examples/example-kotlin/build.gradle
Labels: type: dependency-upgrade

#237 Dependency upgrades
  doc-examples/example-kotlin/build.gradle
Labels: type: dependency-upgrade

#243 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#247 Dependency upgrades
  gcp-logging/build.gradle
Labels: type: dependency-upgrade

#249 [gcp] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#250 [gcp] Update common files for branch 3.1.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#251 bump up micronaut test to 2.0.0
  gcp-common/build.gradle
  gcp-function-http-test/build.gradle
  gcp-http-client/build.gradle
  gcp-logging/build.gradle
  gcp-pubsub/build.gradle
  gcp-tracing/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#262 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade
