Repository micronaut-projects/micronaut-gcp, pull requests merged in 2020-08, with the labels that each got.

#188 Dependency upgrades
  gcp-tracing/build.gradle
Labels: type: dependency-upgrade

#193 [gcp] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#202 [gcp] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#209 [gcp] Update common files for branch 2.1.x
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#208 [gcp] Update common files for branch master
  .github/workflows/release-notes.yml
Labels: relates-to: build

#114 Upgrade to Micronaut 2.x
  doc-examples/example-kotlin/build.gradle
  gcp-function-http/src/main/java/io/micronaut/gcp/function/http/GoogleFunctionHttpResponse.java
  gradle.properties
Labels: status: future consideration
