Repository micronaut-projects/micronaut-gcp, pull requests merged in 2020-10, with the labels that each got.

#264 Dependency upgrades
  gcp-common/build.gradle
  gcp-tracing/build.gradle
Labels: type: dependency-upgrade

#277 [gcp] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#278 [gcp] Update common files for branch 3.1.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#286 Adding message ordering capabilities
  doc-examples/example-groovy/src/main/groovy/io/micronaut/gcp/pubsub/ordering/LocationClient.groovy
  doc-examples/example-groovy/src/main/groovy/io/micronaut/gcp/pubsub/ordering/OrderClient.groovy
  doc-examples/example-groovy/src/main/groovy/io/micronaut/gcp/pubsub/ordering/OrderService.groovy
  doc-examples/example-groovy/src/main/groovy/io/micronaut/gcp/pubsub/support/Order.groovy
  doc-examples/example-java/src/main/java/io/micronaut/gcp/pubsub/ordering/LocationClient.java
  doc-examples/example-java/src/main/java/io/micronaut/gcp/pubsub/ordering/OrderClient.java
  doc-examples/example-java/src/main/java/io/micronaut/gcp/pubsub/ordering/OrderService.java
  doc-examples/example-java/src/main/java/io/micronaut/gcp/pubsub/support/Order.java
  doc-examples/example-kotlin/src/main/kotlin/io/micronaut/gcp/pubsub/ordering/LocationClient.kt
  doc-examples/example-kotlin/src/main/kotlin/io/micronaut/gcp/pubsub/ordering/OrderClient.kt
  doc-examples/example-kotlin/src/main/kotlin/io/micronaut/gcp/pubsub/ordering/OrderService.kt
  doc-examples/example-kotlin/src/main/kotlin/io/micronaut/gcp/pubsub/support/Order.kt
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/annotation/OrderingKey.java
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/annotation/Topic.java
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/intercept/PubSubClientIntroductionAdvice.java
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/support/DefaultPublisherFactory.java
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/support/PubSubPublisherState.java
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/support/PublisherFactoryConfig.java
  gcp-pubsub/src/test/groovy/io/micronaut/gcp/pubsub/AbstractConsumerSpec.groovy
  gcp-pubsub/src/test/groovy/io/micronaut/gcp/pubsub/integration/IntegrationTestSpec.groovy
  gcp-pubsub/src/test/groovy/io/micronaut/gcp/pubsub/integration/MessageOrderingTests.groovy
  src/main/docs/guide/pubsub/ordering.adoc
  src/main/docs/guide/pubsub/pubsubIntroduction.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement
