Repository micronaut-projects/micronaut-gcp, pull requests merged in 2023-09, with the labels that each got.

#920 [gcp] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#908 Multiple possible bean candidates found
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/exception/DefaultPubSubMessageReceiverExceptionHandler.java
  gcp-pubsub/src/test/groovy/io/micronaut/gcp/pubsub/bind/DefaultExceptionHandlerSpec.groovy
Labels: type: bug

#926 [gcp] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#935 docs: duplicated Secret Manager Secret Manager
  src/main/docs/guide/secretManager.adoc
Labels: type: docs

#932 Introduce mechanism to avoid loading default config files
  gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/SecretManagerConfigurationClient.java
  gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/configuration/SecretManagerConfigurationProperties.java
  gcp-secret-manager/src/test/groovy/io/micronaut/gcp/secretmanager/SecretManagerConfigSpec.groovy
  src/main/docs/guide/secretManager/distributedConfiguration.adoc
Labels: type: improvement
