Repository micronaut-projects/micronaut-gcp, pull requests merged in 2023-08, with the labels that each got.

#901 Remove unnecessary version numbers from docs.
  src/main/docs/guide/cloudFunction/httpFunctions.adoc
  src/main/docs/guide/cloudFunction/simpleFunctions.adoc
  src/main/docs/guide/logging.adoc
  src/main/docs/guide/setup.adoc
  src/main/docs/guide/tracing.adoc
Labels: type: docs

#905 [gcp] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#914 fix: close server application context
  gcp-function-http-test/src/main/java/io/micronaut/gcp/function/http/test/InvokerHttpServer.java
Labels: type: bug

#916 Lookup the JsonMapper lazily
  gcp-logging/src/main/java/io/micronaut/gcp/logging/StackdriverJsonLayout.java
Labels: type: bug
