Repository micronaut-projects/micronaut-gcp, pull requests merged in 2023-02, with the labels that each got.

#764 Migrate to new configuration asciidoc macro and build plugin 5.4.x
  .github/workflows/graalvm.yml
  settings.gradle
  src/main/docs/guide/authorizingClients.adoc
  src/main/docs/guide/pubsub/executors.adoc
  src/main/docs/guide/pubsub/producer/publisherProperties.adoc
  src/main/docs/guide/pubsub/pullConsumer/subscriberProperties.adoc
  src/main/docs/guide/secretManager/distributedConfiguration.adoc
  src/main/docs/guide/tracing.adoc
Labels: type: docs

#759 [gcp] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#635 Add support for specifying default Topic endpoint
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/annotation/Topic.java
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/configuration/PubSubConfigurationProperties.java
  gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/intercept/PubSubClientIntroductionAdvice.java
  gcp-pubsub/src/test/groovy/io/micronaut/gcp/pubsub/configuration/PubSubConfigurationSpec.groovy
  src/main/docs/guide/pubsub/ordering.adoc
Labels: type: enhancement
