Repository micronaut-projects/micronaut-gcp, pull requests merged in 2025-03, with the labels that each got.

#1290 GCP to Core 4.8.x
  gcp-function-http-test/build.gradle
  gcp-function-http/src/main/java/io/micronaut/gcp/function/http/GoogleFunctionHttpRequest.java
  gcp-function-http/src/main/java/io/micronaut/gcp/function/http/HttpFunction.java
  gcp-function-http/src/test/groovy/io/micronaut/gcp/function/http/ParameterBindingSpec.groovy
  gradle/libs.versions.toml
  test-suite-http-server-tck-gcp-function-http/src/test/java/io/micronaut/http/server/tck/gcp/function/tests/GcpFunctionHttpServerTestSuite.java
Labels: type: dependency-upgrade

#1304 [gcp] Update common files for branch 5.9.x
  gradle/wrapper/gradle-wrapper.jar
  gradlew
Labels: relates-to: build

#1309 breaks: gcp-function-http-test based on HTTP Server instead of Jetty 11
  buildSrc/src/main/groovy/io.micronaut.build.internal.gcp-module.gradle
  gcp-function-http-test/build.gradle
  gcp-function-http-test/src/main/java/io/micronaut/gcp/function/http/test/EmbeddedServerFactory.java
  gcp-function-http-test/src/main/java/io/micronaut/gcp/function/http/test/GoogleCloudFunctionHttpHandler.java
  gcp-function-http-test/src/main/java/io/micronaut/gcp/function/http/test/HttpExchangeHttpRequest.java
  gcp-function-http-test/src/main/java/io/micronaut/gcp/function/http/test/HttpExchangeHttpResponse.java
  gcp-function-http-test/src/main/java/io/micronaut/gcp/function/http/test/HttpRequestImpl.java
  gcp-function-http-test/src/main/java/io/micronaut/gcp/function/http/test/HttpResponseImpl.java
  gcp-function-http-test/src/main/java/io/micronaut/gcp/function/http/test/InvokerHttpServer.java
  gcp-function-http/build.gradle
  gradle/libs.versions.toml
  test-suite-http-server-tck-gcp-function-http-test/build.gradle.kts
  test-suite-http-server-tck-gcp-function-http-test/src/test/java/io/micronaut/http/server/tck/gcp/function/GcpFunctionHttpTestServerUnderTest.java
  test-suite-http-server-tck-gcp-function-http-test/src/test/java/io/micronaut/http/server/tck/gcp/function/GcpFunctionHttpTestServerUnderTestProvider.java
  test-suite-http-server-tck-gcp-function-http-test/src/test/java/io/micronaut/http/server/tck/gcp/function/tests/GcpFunctionHttpTestServerTestSuite.java
  test-suite-http-server-tck-gcp-function-http-test/src/test/resources/META-INF/services/io.micronaut.http.tck.ServerUnderTestProvider
Labels: type: breaking
